// Console Color
module.exports.reset = '\x1b[0m'
module.exports.bright = '\x1b[1m'
module.exports.dim = '\x1b[2m'
module.exports.underscore = '\x1b[4m'
module.exports.blink = '\x1b[5m'
module.exports.reverse = '\x1b[7m'
module.exports.hidden = '\x1b[8m'

// Defealt Color
module.exports.black = '\x1b[30m'
module.exports.red = '\x1b[31m'
module.exports.green = '\x1b[32m'
module.exports.yellow = '\x1b[33m'
module.exports.blue = '\x1b[34m'
module.exports.magenta = '\x1b[35m'
module.exports.cyan = '\x1b[36m'
module.exports.white = '\x1b[37m'
module.exports.gray = '\x1b[90m'

// Secret Color
module.exports.BgBlack = '\x1b[40m'
module.exports.BgRed = '\x1b[41m'
module.exports.BgGreen = '\x1b[42m'
module.exports.BgYellow = '\x1b[43m'
module.exports.BgBlue = '\x1b[44m'
module.exports.BgMagenta = '\x1b[45m'
module.exports.BgCyan = '\x1b[46m'
module.exports.BgWhite = '\x1b[47m'